version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: taara_monitoring
      POSTGRES_USER: taara_user
      POSTGRES_PASSWORD: taara_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://taara_user:taara_password@postgres:5432/taara_monitoring
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    restart: unless-stopped
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  scheduler:
    build: .
    environment:
      - DATABASE_URL=postgresql://taara_user:taara_password@postgres:5432/taara_monitoring
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    restart: unless-stopped
    command: python scheduler.py

volumes:
  postgres_data:
